### PR TITLE
Migrate to package:ffi 1.0.0

### PR DESCRIPTION
**Pull request by dcharkes**
Makes this package compatible with Dart 2.12 and package:ffi 1.0.0.

Tested locally on iPod.

### CODE REVIEW

**Comment by dcharkes** [comment]
@am15h, CI for Android fails with requiring Dart 2.7, can we update this to Dart 2.12-beta.9?

(Also, the iOS CI fails completely and has been for a while looking at past commits.)

@mit-mit PTAL at the migration.

**Comment by larsaars** [comment]
I just added an issue to that topic and wanted to make a PR, then I saw yours. Phew!

**Comment by am15h** [comment]
@dcharkes Thanks a lot for the PR.

> @am15h, CI for Android fails with requiring Dart 2.7, can we update this to Dart 2.12-beta.9?

Sure, I will update this.

> (Also, the iOS CI fails completely and has been for a while looking at past commits.)
> 
> 

The current setup using GitHub actions isn't working well, it requires constantly updating the ios device version and some time ago it started exiting flutter driver after executing some intitial tests, [(I tried to troubleshoot it here)](https://github.com/am15h/tflite_flutter_plugin/runs/1817828062). 
I am planning to shift CI to code magic. Please let me know if there is a better option.

**Comment by dcharkes** [comment]
> @dcharkes Thanks a lot for the PR.
> 
> > @am15h, CI for Android fails with requiring Dart 2.7, can we update this to Dart 2.12-beta.9?
> 
> Sure, I will update this.
> 
> > (Also, the iOS CI fails completely and has been for a while looking at past commits.)
> 
> The current setup using GitHub actions isn't working well, it requires constantly updating the ios device version and some time ago it started exiting flutter driver after executing some intitial tests, [(I tried to troubleshoot it here)](https://github.com/am15h/tflite_flutter_plugin/runs/1817828062).
> I am planning to shift CI to code magic. Please let me know if there is a better option.

cc @mannprerak2 how does our setup on package:ffigen work?

**Comment by mannprerak2** [comment]
@dcharkes the CI for package:ffigen is much simpler than this one, since we only run dart tests, the initial setup is also quite simple since all we need to do is install libclang (llvm), overall structure however seems similar.

The errors all seem very weird to me, I think code magic might be better, especially when it comes to iOS, but I don't have any experience to say.

**Comment by dcharkes** [comment]
> Sure, I will update this.

Okay, let's see if the Android CI turns green after that.

> @dcharkes the CI for package:ffigen is much simpler than this one, since we only run dart tests, the initial setup is also quite simple since all we need to do is install libclang (llvm).

Ah yeah, of course. We don't do any Flutter things on that repo.

**Comment by am15h** [comment]
@dcharkes Thanks again for this migration, I have merged the PR and updated the CI workflow, unfortunately it is still failing. **Logs:** https://github.com/am15h/tflite_flutter_plugin/runs/2020313197?check_suite_focus=true

**Comment by dcharkes** [comment]
Hey, now that Flutter 2 is released, can you try bumping the SDK constraint to Flutter 2? I'd hope Flutter driver is migrated to null-safety in the release.

Alternatively, you could pass the [--no-sound-null-safety flag](https://dart.dev/null-safety/unsound-null-safety#testing-or-running-mixed-version-programs).

Let me know if you need more help.

**Comment by am15h** [comment]
Unfortunately, these two steps do not resolve the error. You may have a look at the latest 3 commits in [`update_workflow` branch](https://github.com/am15h/tflite_flutter_plugin/commits/update_workflow) and [latest logs](https://github.com/am15h/tflite_flutter_plugin/pull/83/checks?check_run_id=2046143730)

**Comment by mannprerak2** [comment]
Seems like the flutter driver doesn't run with sound null safety yet.

**Comment by tomk9** [comment]
@am15h Will you publish it on pub.dev as 0.6.0 version?

**Comment by am15h** [comment]
Sorry for the delay @tomk9, v0.6.0 is now published. 

Thanks @dcharkes for the PR and @mannprerak2 for the help in fixing ci. Android is now green.

**Pull request merged**
